export const actionTypes = {
  FETCH_TV_SHOWS: 'FETCH_TV_SHOWS',
  FETCH_SINGLE_TV_SHOW: 'FETCH_SINGLE_TV_SHOW',
  ADD_TV_SHOW_TO_FAVORITES: 'ADD_TV_SHOW_TO_FAVORITES',
  REMOVE_TV_SHOW_FROM_FAVORITES: 'REMOVE_TV_SHOW_FROM_FAVORITES'
}

export const getterTypes = {
  TV_SHOWS: 'TV_SHOWS',
  TV_SHOWS_LOADING: 'TV_SHOWS_LOADING',
  TV_SHOWS_ERROR: 'TV_SHOWS_ERROR'
}

// TODO: explain how to use mutations in store
export const mutationTypes = {
  SET_TV_SHOWS: 'SET_TV_SHOWS',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  SET_TO_FAVORITE: 'SET_TO_FAVORITE',
  REMOVE_FROM_FAVORITE: 'REMOVE_FROM_FAVORITE',
  ADD_TV_SHOW: 'ADD_TV_SHOW'
}
